from fastapi import FastAPI
from fastapi.responses import HTMLResponse
app=FastAPI(title='Fleet Health Console')
SERVERS=[{'name':'edge-01','model':'DL360 Gen11','health':'OK'},{'name':'edge-02','model':'DL380 Gen11','health':'Warning'},{'name':'db-01','model':'DL360 Gen11','health':'Critical'},{'name':'api-01','model':'DL380 Gen11','health':'OK'}]
@app.get('/health')
def health(): return {'status':'ok'}
@app.get('/api/servers')
def servers(): return SERVERS
@app.get('/',response_class=HTMLResponse)
def home():
    return HTMLResponse('''<!doctype html><html><head><meta charset='utf-8'><title>Fleet Health</title><style>body{font-family:Arial;margin:40px;max-width:900px;background:#0f172a;color:#e2e8f0}h1{color:#f8fafc}.controls{display:flex;gap:16px;align-items:end;flex-wrap:wrap;margin:16px 0}.field{display:flex;flex-direction:column;gap:6px}label{color:#cbd5e1;font-weight:600}select,input{background:#1e293b;color:#e2e8f0;border:1px solid #334155;border-radius:6px;padding:8px 10px}select:focus,input:focus{outline:2px solid #38bdf8;outline-offset:1px}.server{border-bottom:1px solid #334155;padding:10px}.health{font-weight:700;color:#93c5fd}#summary{margin:10px 0;font-weight:700;color:#bae6fd}#no-results{min-height:1.5em;margin:6px 0;color:#fca5a5}</style></head><body><h1>Fleet Health Console</h1><div class='controls'><div class='field'><label for='health-filter'>Health</label><select id='health-filter'><option value='All'>All</option><option value='OK'>OK</option><option value='Warning'>Warning</option><option value='Critical'>Critical</option></select></div><div class='field'><label for='search'>Search name or model</label><input id='search' type='text' placeholder='DL360'></div></div><div id='summary'></div><div id='no-results' role='status' aria-live='polite'></div><div id='servers'></div><script>const healthFilter=document.getElementById('health-filter');const search=document.getElementById('search');const summary=document.getElementById('summary');const noResults=document.getElementById('no-results');const servers=document.getElementById('servers');let allServers=[];function matches(x,health,query){const matchHealth=health==='All'||x.health===health;const q=query.trim().toLowerCase();const target=`${x.name} ${x.model}`.toLowerCase();const matchQuery=q===''||target.includes(q);return matchHealth&&matchQuery;}function render(){const health=healthFilter.value;const query=search.value;const visible=allServers.filter(x=>matches(x,health,query));summary.textContent=`${visible.length} of ${allServers.length} servers`;noResults.textContent=visible.length===0?'No matching servers found.':'';servers.innerHTML=visible.map(x=>`<div class='server' data-testid='server-row'><strong>${x.name}</strong> — ${x.model} — <span class='health'>${x.health}</span></div>`).join('');}async function load(){allServers=await (await fetch('/api/servers')).json();healthFilter.addEventListener('change',render);search.addEventListener('input',render);render();}load();</script></body></html>''')
